# This is a docker compose file for running the project locally
services:
  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - local-network

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    networks:
      - local-network

volumes:
  postgres_data:
    driver: local
  
networks:
  local-network:
    driver: bridge
    
