// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	languages: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * T​i​ế​n​g​ ​V​i​ệ​t
		 */
		vi: string
	}
	breadcrumb: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * A​d​m​i​n
		 */
		admin: string
		/**
		 * U​s​e​r​s
		 */
		users: string
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​s
		 */
		organizations: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * G​e​n​e​r​a​l
		 */
		settingsGeneral: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n
		 */
		settingsNotification: string
		/**
		 * A​d​v​a​n​c​e​d
		 */
		settingsAdvance: string
		/**
		 * S​e​c​u​r​i​t​y
		 */
		settingsSecurity: string
		/**
		 * P​o​s​t​s
		 */
		posts: string
		/**
		 * C​a​t​e​g​o​r​i​e​s
		 */
		categories: string
		/**
		 * M​e​m​b​e​r​s
		 */
		members: string
		/**
		 * I​n​v​i​t​a​t​i​o​n​s
		 */
		invitations: string
		/**
		 * R​e​p​o​r​t​s
		 */
		reports: string
		/**
		 * N​e​w
		 */
		'new': string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * P​o​s​t
		 */
		post: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		category: string
	}
	sidebar: {
		/**
		 * P​l​a​t​f​o​r​m
		 */
		platform: string
		/**
		 * C​o​n​t​e​n​t
		 */
		content: string
		/**
		 * P​o​s​t​s
		 */
		posts: string
		/**
		 * C​a​t​e​g​o​r​i​e​s
		 */
		categories: string
		/**
		 * T​e​a​m
		 */
		team: string
		/**
		 * M​e​m​b​e​r​s
		 */
		members: string
		/**
		 * I​n​v​i​t​a​t​i​o​n​s
		 */
		invitations: string
		/**
		 * I​n​s​i​g​h​t​s
		 */
		insights: string
		/**
		 * R​e​p​o​r​t​s
		 */
		reports: string
	}
	adminSidebar: {
		/**
		 * A​d​m​i​n​i​s​t​r​a​t​i​o​n
		 */
		administration: string
		/**
		 * U​s​e​r​s
		 */
		users: string
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​s
		 */
		organizations: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * G​e​n​e​r​a​l
		 */
		settingsGeneral: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n
		 */
		settingsNotification: string
		/**
		 * A​d​v​a​n​c​e​d
		 */
		settingsAdvance: string
		/**
		 * S​e​c​u​r​i​t​y
		 */
		settingsSecurity: string
	}
	adminHeader: {
		/**
		 * E​x​i​t​ ​a​d​m​i​n
		 */
		exitAdmin: string
	}
}

export type TranslationFunctions = {
	languages: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Tiếng Việt
		 */
		vi: () => LocalizedString
	}
	breadcrumb: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Admin
		 */
		admin: () => LocalizedString
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * Organizations
		 */
		organizations: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * General
		 */
		settingsGeneral: () => LocalizedString
		/**
		 * Notification
		 */
		settingsNotification: () => LocalizedString
		/**
		 * Advanced
		 */
		settingsAdvance: () => LocalizedString
		/**
		 * Security
		 */
		settingsSecurity: () => LocalizedString
		/**
		 * Posts
		 */
		posts: () => LocalizedString
		/**
		 * Categories
		 */
		categories: () => LocalizedString
		/**
		 * Members
		 */
		members: () => LocalizedString
		/**
		 * Invitations
		 */
		invitations: () => LocalizedString
		/**
		 * Reports
		 */
		reports: () => LocalizedString
		/**
		 * New
		 */
		'new': () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Post
		 */
		post: () => LocalizedString
		/**
		 * Category
		 */
		category: () => LocalizedString
	}
	sidebar: {
		/**
		 * Platform
		 */
		platform: () => LocalizedString
		/**
		 * Content
		 */
		content: () => LocalizedString
		/**
		 * Posts
		 */
		posts: () => LocalizedString
		/**
		 * Categories
		 */
		categories: () => LocalizedString
		/**
		 * Team
		 */
		team: () => LocalizedString
		/**
		 * Members
		 */
		members: () => LocalizedString
		/**
		 * Invitations
		 */
		invitations: () => LocalizedString
		/**
		 * Insights
		 */
		insights: () => LocalizedString
		/**
		 * Reports
		 */
		reports: () => LocalizedString
	}
	adminSidebar: {
		/**
		 * Administration
		 */
		administration: () => LocalizedString
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * Organizations
		 */
		organizations: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * General
		 */
		settingsGeneral: () => LocalizedString
		/**
		 * Notification
		 */
		settingsNotification: () => LocalizedString
		/**
		 * Advanced
		 */
		settingsAdvance: () => LocalizedString
		/**
		 * Security
		 */
		settingsSecurity: () => LocalizedString
	}
	adminHeader: {
		/**
		 * Exit admin
		 */
		exitAdmin: () => LocalizedString
	}
}

export type Formatters = {}
