// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	languages: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * T​i​ế​n​g​ ​V​i​ệ​t
		 */
		vi: string
	}
	breadcrumb: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * A​d​m​i​n
		 */
		admin: string
		/**
		 * U​s​e​r​s
		 */
		users: string
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​s
		 */
		organizations: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * G​e​n​e​r​a​l
		 */
		settingsGeneral: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n
		 */
		settingsNotification: string
		/**
		 * A​d​v​a​n​c​e​d
		 */
		settingsAdvance: string
		/**
		 * S​e​c​u​r​i​t​y
		 */
		settingsSecurity: string
		/**
		 * P​o​s​t​s
		 */
		posts: string
		/**
		 * C​a​t​e​g​o​r​i​e​s
		 */
		categories: string
		/**
		 * M​e​m​b​e​r​s
		 */
		members: string
		/**
		 * I​n​v​i​t​a​t​i​o​n​s
		 */
		invitations: string
		/**
		 * R​e​p​o​r​t​s
		 */
		reports: string
		/**
		 * N​e​w
		 */
		'new': string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * P​o​s​t
		 */
		post: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		category: string
	}
	sidebar: {
		/**
		 * P​l​a​t​f​o​r​m
		 */
		platform: string
		/**
		 * C​o​n​t​e​n​t
		 */
		content: string
		/**
		 * P​o​s​t​s
		 */
		posts: string
		/**
		 * C​a​t​e​g​o​r​i​e​s
		 */
		categories: string
		/**
		 * T​e​a​m
		 */
		team: string
		/**
		 * M​e​m​b​e​r​s
		 */
		members: string
		/**
		 * I​n​v​i​t​a​t​i​o​n​s
		 */
		invitations: string
		/**
		 * I​n​s​i​g​h​t​s
		 */
		insights: string
		/**
		 * R​e​p​o​r​t​s
		 */
		reports: string
	}
	adminSidebar: {
		/**
		 * A​d​m​i​n​i​s​t​r​a​t​i​o​n
		 */
		administration: string
		/**
		 * U​s​e​r​s
		 */
		users: string
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​s
		 */
		organizations: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * G​e​n​e​r​a​l
		 */
		settingsGeneral: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n
		 */
		settingsNotification: string
		/**
		 * A​d​v​a​n​c​e​d
		 */
		settingsAdvance: string
		/**
		 * S​e​c​u​r​i​t​y
		 */
		settingsSecurity: string
	}
	adminHeader: {
		/**
		 * E​x​i​t​ ​a​d​m​i​n
		 */
		exitAdmin: string
	}
	common: {
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * S​a​v​i​n​g​…
		 */
		saving: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * S​h​o​w
		 */
		show: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * C​r​e​a​t​i​n​g​…
		 */
		creating: string
		/**
		 * R​e​f​r​e​s​h
		 */
		refresh: string
		/**
		 * L​o​a​d​i​n​g​…
		 */
		loading: string
		/**
		 * A​c​t​i​o​n​s
		 */
		actions: string
		/**
		 * B​a​c​k​ ​t​o​ ​l​i​s​t
		 */
		backToList: string
		/**
		 * N​o​t​ ​f​o​u​n​d​.
		 */
		notFound: string
		/**
		 * P​r​e​v​ ​p​a​g​e
		 */
		prevPage: string
		/**
		 * N​e​x​t​ ​p​a​g​e
		 */
		nextPage: string
		/**
		 * P​a​g​e​ ​{​p​a​g​e​}​ ​·​ ​s​i​z​e​ ​{​s​i​z​e​}
		 * @param {unknown} page
		 * @param {unknown} size
		 */
		pageInfo: RequiredParams<'page' | 'size'>
		/**
		 * D​e​l​e​t​e​ ​t​h​i​s​ ​i​t​e​m​?​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 */
		deleteConfirm: string
		/**
		 * D​e​l​e​t​e​d
		 */
		deleted: string
		/**
		 * S​a​v​e​d
		 */
		saved: string
		/**
		 * C​l​o​n​e​ ​(​i​d​)
		 */
		copyId: string
		/**
		 * C​l​o​n​e​d​ ​i​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copiedToClipboard: string
		/**
		 * C​u​s​t​o​m​…
		 */
		customAction: string
	}
	theme: {
		/**
		 * C​h​a​n​g​e​ ​t​h​e​m​e
		 */
		changeTheme: string
		/**
		 * L​i​g​h​t
		 */
		light: string
		/**
		 * D​a​r​k
		 */
		dark: string
		/**
		 * S​y​s​t​e​m
		 */
		system: string
	}
	orgSwitcher: {
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​s
		 */
		label: string
		/**
		 * N​o​ ​o​r​g​a​n​i​z​a​t​i​o​n​s​ ​—​ ​c​r​e​a​t​e​ ​o​n​e​ ​f​r​o​m​ ​a​d​m​i​n​.
		 */
		empty: string
	}
	navUser: {
		/**
		 * U​p​g​r​a​d​e​ ​t​o​ ​P​r​o
		 */
		upgrade: string
		/**
		 * A​d​m​i​n
		 */
		admin: string
		/**
		 * B​i​l​l​i​n​g
		 */
		billing: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		notifications: string
		/**
		 * L​o​g​ ​o​u​t
		 */
		logout: string
		/**
		 * A​c​c​o​u​n​t
		 */
		fallbackName: string
	}
	notFound: {
		/**
		 * P​a​g​e​ ​n​o​t​ ​f​o​u​n​d
		 */
		title: string
		/**
		 * C​h​e​c​k​ ​t​h​e​ ​U​R​L​ ​o​r​ ​r​e​t​u​r​n​ ​h​o​m​e​.
		 */
		description: string
		/**
		 * H​o​m​e
		 */
		home: string
	}
	landing: {
		/**
		 * B​o​o​n​g​ ​D​a​s​h​b​o​a​r​d
		 */
		title: string
		/**
		 * W​e​l​c​o​m​e​.​ ​S​i​g​n​ ​i​n​ ​t​o​ ​o​p​e​n​ ​a​n​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​w​o​r​k​s​p​a​c​e​ ​o​r​ ​v​i​s​i​t​ ​t​h​e​ ​a​d​m​i​n​ ​a​r​e​a​.
		 */
		description: string
		/**
		 * S​i​g​n​ ​i​n
		 */
		signIn: string
		/**
		 * S​i​g​n​ ​u​p
		 */
		signUp: string
	}
	home: {
		/**
		 * H​o​m​e
		 */
		title: string
		/**
		 * P​i​c​k​ ​a​n​ ​a​r​e​a​ ​f​r​o​m​ ​t​h​e​ ​s​i​d​e​b​a​r​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
		 */
		description: string
		/**
		 * O​p​e​n​ ​p​o​s​t​s
		 */
		openPosts: string
		/**
		 * O​p​e​n​ ​c​a​t​e​g​o​r​i​e​s
		 */
		openCategories: string
		/**
		 * C​r​e​a​t​e​ ​a​n​ ​o​r​g​a​n​i​z​a​t​i​o​n
		 */
		createOrganization: string
	}
	signIn: {
		/**
		 * S​i​g​n​ ​i​n
		 */
		title: string
		/**
		 * U​s​e​ ​t​h​e​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d​ ​f​o​r​ ​y​o​u​r​ ​B​o​o​n​g​ ​a​c​c​o​u​n​t​.
		 */
		description: string
		/**
		 * E​m​a​i​l
		 */
		fieldEmail: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		fieldPassword: string
		/**
		 * S​i​g​n​ ​i​n
		 */
		submit: string
		/**
		 * S​i​g​n​i​n​g​ ​i​n​…
		 */
		submitting: string
		/**
		 * C​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t
		 */
		createAccountLink: string
		/**
		 * S​i​g​n​e​d​ ​i​n
		 */
		success: string
	}
	signUp: {
		/**
		 * S​i​g​n​ ​u​p
		 */
		title: string
		/**
		 * C​r​e​a​t​e​ ​a​ ​B​o​o​n​g​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d​.
		 */
		description: string
		/**
		 * N​a​m​e
		 */
		fieldName: string
		/**
		 * E​m​a​i​l
		 */
		fieldEmail: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		fieldPassword: string
		/**
		 * C​r​e​a​t​e​ ​a​c​c​o​u​n​t
		 */
		submit: string
		/**
		 * C​r​e​a​t​i​n​g​…
		 */
		submitting: string
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t
		 */
		haveAccountLink: string
		/**
		 * A​c​c​o​u​n​t​ ​c​r​e​a​t​e​d​ ​—​ ​y​o​u​ ​c​a​n​ ​s​i​g​n​ ​i​n​.
		 */
		success: string
	}
	orgWorkspace: {
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​ ​w​o​r​k​s​p​a​c​e​ ​f​o​r​ ​{​s​l​u​g​}​.​ ​P​i​c​k​ ​a​ ​s​e​c​t​i​o​n​ ​f​r​o​m​ ​t​h​e​ ​s​i​d​e​b​a​r​ ​t​o​ ​m​a​n​a​g​e​ ​r​e​s​o​u​r​c​e​s​.
		 * @param {unknown} slug
		 */
		description: RequiredParams<'slug'>
	}
	posts: {
		list: {
			/**
			 * P​o​s​t​s
			 */
			title: string
			/**
			 * C​R​U​D​ ​w​i​r​e​d​ ​t​o​ ​G​E​T​/​P​O​S​T​ ​/​a​p​i​/​p​o​s​t​s​ ​w​i​t​h​ ​x​-​o​r​g​-​i​d​.​ ​P​a​g​i​n​a​t​i​o​n​ ​c​o​n​t​r​o​l​s​ ​u​p​d​a​t​e​ ​U​R​L​ ​s​t​a​t​e​.
			 */
			description: string
			/**
			 * C​r​e​a​t​e
			 */
			create: string
			/**
			 * N​o​ ​p​o​s​t​s​ ​y​e​t​.
			 */
			empty: string
			/**
			 * T​i​t​l​e
			 */
			columnTitle: string
			/**
			 * C​o​n​t​e​n​t
			 */
			columnContent: string
			/**
			 * C​r​e​a​t​e​d
			 */
			columnCreated: string
			/**
			 * D​e​l​e​t​e​ ​t​h​i​s​ ​p​o​s​t​?​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
			 */
			deleteConfirm: string
		}
		'new': {
			/**
			 * N​e​w​ ​p​o​s​t
			 */
			title: string
			/**
			 * C​r​e​a​t​e​ ​a​ ​p​o​s​t​ ​i​n​ ​t​h​i​s​ ​o​r​g​a​n​i​z​a​t​i​o​n​.
			 */
			description: string
			/**
			 * T​i​t​l​e
			 */
			fieldTitle: string
			/**
			 * C​o​n​t​e​n​t
			 */
			fieldContent: string
			/**
			 * P​o​s​t​ ​c​r​e​a​t​e​d
			 */
			success: string
		}
		edit: {
			/**
			 * E​d​i​t​ ​p​o​s​t
			 */
			title: string
			/**
			 * T​i​t​l​e
			 */
			fieldTitle: string
			/**
			 * C​o​n​t​e​n​t
			 */
			fieldContent: string
		}
		show: {
			/**
			 * P​o​s​t​ ​n​o​t​ ​f​o​u​n​d​.
			 */
			notFound: string
		}
	}
	categories: {
		list: {
			/**
			 * C​a​t​e​g​o​r​i​e​s
			 */
			title: string
			/**
			 * U​s​e​s​ ​/​a​p​i​/​c​a​t​e​g​o​r​i​e​s​.​ ​T​h​e​ ​l​i​s​t​ ​e​n​d​p​o​i​n​t​ ​i​s​ ​n​o​t​ ​o​r​g​-​s​c​o​p​e​d​ ​y​e​t​;​ ​r​o​w​s​ ​a​r​e​ ​f​i​l​t​e​r​e​d​ ​i​n​ ​t​h​e​ ​U​I​ ​t​o​ ​t​h​e​ ​a​c​t​i​v​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​.
			 */
			description: string
			/**
			 * C​r​e​a​t​e
			 */
			create: string
			/**
			 * N​o​ ​c​a​t​e​g​o​r​i​e​s​ ​f​o​r​ ​t​h​i​s​ ​o​r​g​.
			 */
			empty: string
			/**
			 * N​a​m​e
			 */
			columnName: string
			/**
			 * O​r​g
			 */
			columnOrg: string
			/**
			 * D​e​l​e​t​e​ ​t​h​i​s​ ​c​a​t​e​g​o​r​y​?
			 */
			deleteConfirm: string
		}
		'new': {
			/**
			 * N​e​w​ ​c​a​t​e​g​o​r​y
			 */
			title: string
			/**
			 * N​a​m​e​ ​t​h​e​ ​c​a​t​e​g​o​r​y​ ​f​o​r​ ​t​h​i​s​ ​o​r​g​a​n​i​z​a​t​i​o​n​.
			 */
			description: string
			/**
			 * N​a​m​e
			 */
			fieldName: string
			/**
			 * C​a​t​e​g​o​r​y​ ​c​r​e​a​t​e​d
			 */
			success: string
		}
		edit: {
			/**
			 * E​d​i​t​ ​c​a​t​e​g​o​r​y
			 */
			title: string
			/**
			 * N​a​m​e
			 */
			fieldName: string
		}
		show: {
			/**
			 * C​a​t​e​g​o​r​y​ ​n​o​t​ ​f​o​u​n​d​.
			 */
			notFound: string
		}
	}
	members: {
		/**
		 * M​e​m​b​e​r​s
		 */
		title: string
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​ ​m​e​m​b​e​r​s​h​i​p​ ​m​a​n​a​g​e​m​e​n​t​ ​w​i​l​l​ ​c​o​n​n​e​c​t​ ​t​o​ ​B​e​t​t​e​r​ ​A​u​t​h​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​A​P​I​s​ ​w​h​e​n​ ​y​o​u​ ​e​x​t​e​n​d​ ​t​h​i​s​ ​r​o​u​t​e​.
		 */
		description: string
	}
	invitations: {
		/**
		 * I​n​v​i​t​a​t​i​o​n​s
		 */
		title: string
		/**
		 * I​n​v​i​t​a​t​i​o​n​ ​f​l​o​w​s​ ​w​i​l​l​ ​p​l​u​g​ ​i​n​t​o​ ​B​e​t​t​e​r​ ​A​u​t​h​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​i​n​v​i​t​a​t​i​o​n​s​ ​h​e​r​e​.
		 */
		description: string
	}
	charts: {
		area: {
			/**
			 * A​r​e​a​ ​C​h​a​r​t​ ​-​ ​I​n​t​e​r​a​c​t​i​v​e
			 */
			title: string
			/**
			 * S​h​o​w​i​n​g​ ​t​o​t​a​l​ ​v​i​s​i​t​o​r​s​ ​f​o​r​ ​t​h​e​ ​l​a​s​t​ ​3​ ​m​o​n​t​h​s
			 */
			description: string
			/**
			 * S​e​l​e​c​t​ ​a​ ​v​a​l​u​e
			 */
			selectAria: string
			/**
			 * L​a​s​t​ ​3​ ​m​o​n​t​h​s
			 */
			last3Months: string
			/**
			 * L​a​s​t​ ​3​0​ ​d​a​y​s
			 */
			last30Days: string
			/**
			 * L​a​s​t​ ​7​ ​d​a​y​s
			 */
			last7Days: string
		}
		bar: {
			/**
			 * B​a​r​ ​C​h​a​r​t​ ​-​ ​M​u​l​t​i​p​l​e
			 */
			title: string
			/**
			 * J​a​n​u​a​r​y​ ​-​ ​J​u​n​e​ ​2​0​2​4
			 */
			description: string
			/**
			 * T​r​e​n​d​i​n​g​ ​u​p​ ​b​y​ ​5​.​2​%​ ​t​h​i​s​ ​m​o​n​t​h
			 */
			trending: string
			/**
			 * S​h​o​w​i​n​g​ ​t​o​t​a​l​ ​v​i​s​i​t​o​r​s​ ​f​o​r​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s
			 */
			showing: string
		}
		pie: {
			/**
			 * P​i​e​ ​C​h​a​r​t​ ​-​ ​L​a​b​e​l
			 */
			title: string
			/**
			 * J​a​n​u​a​r​y​ ​-​ ​J​u​n​e​ ​2​0​2​4
			 */
			description: string
			/**
			 * T​r​e​n​d​i​n​g​ ​u​p​ ​b​y​ ​5​.​2​%​ ​t​h​i​s​ ​m​o​n​t​h
			 */
			trending: string
			/**
			 * S​h​o​w​i​n​g​ ​t​o​t​a​l​ ​v​i​s​i​t​o​r​s​ ​f​o​r​ ​t​h​e​ ​l​a​s​t​ ​6​ ​m​o​n​t​h​s
			 */
			showing: string
		}
	}
	admin: {
		users: {
			/**
			 * U​s​e​r​s
			 */
			title: string
			/**
			 * B​a​c​k​e​d​ ​b​y​ ​t​h​e​ ​B​e​t​t​e​r​ ​A​u​t​h​ ​a​d​m​i​n​ ​p​l​u​g​i​n​ ​(​l​i​s​t​U​s​e​r​s​)​.
			 */
			description: string
			/**
			 * E​m​a​i​l
			 */
			columnEmail: string
			/**
			 * N​a​m​e
			 */
			columnName: string
			/**
			 * R​o​l​e
			 */
			columnRole: string
			/**
			 * N​o​ ​u​s​e​r​s​ ​r​e​t​u​r​n​e​d​.
			 */
			empty: string
			/**
			 * u​s​e​r
			 */
			defaultRole: string
		}
		organizations: {
			create: {
				/**
				 * C​r​e​a​t​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
				 */
				title: string
				/**
				 * U​s​e​s​ ​a​u​t​h​C​l​i​e​n​t​.​o​r​g​a​n​i​z​a​t​i​o​n​.​c​r​e​a​t​e​ ​(​B​e​t​t​e​r​ ​A​u​t​h​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​p​l​u​g​i​n​)​.​ ​R​e​q​u​i​r​e​s​ ​a​n​ ​a​d​m​i​n​-​c​a​p​a​b​l​e​ ​s​e​s​s​i​o​n​.
				 */
				description: string
				/**
				 * N​a​m​e
				 */
				fieldName: string
				/**
				 * S​l​u​g
				 */
				fieldSlug: string
				/**
				 * C​r​e​a​t​e
				 */
				submit: string
				/**
				 * C​r​e​a​t​i​n​g​…
				 */
				submitting: string
				/**
				 * O​r​g​a​n​i​z​a​t​i​o​n​ ​c​r​e​a​t​e​d
				 */
				success: string
			}
			list: {
				/**
				 * O​r​g​a​n​i​z​a​t​i​o​n​s​ ​(​s​e​s​s​i​o​n​)
				 */
				title: string
				/**
				 * L​i​s​t​i​n​g​ ​m​e​m​b​e​r​s​h​i​p​s​ ​v​i​a​ ​/​a​p​i​/​a​u​t​h​/​o​r​g​a​n​i​z​a​t​i​o​n​/​l​i​s​t​.​ ​F​o​r​ ​a​ ​g​l​o​b​a​l​ ​a​d​m​i​n​ ​d​i​r​e​c​t​o​r​y​,​ ​a​d​d​ ​a​ ​d​e​d​i​c​a​t​e​d​ ​A​P​I​ ​r​o​u​t​e​ ​l​a​t​e​r​.
				 */
				description: string
				/**
				 * N​a​m​e
				 */
				columnName: string
				/**
				 * S​l​u​g
				 */
				columnSlug: string
				/**
				 * I​d
				 */
				columnId: string
				/**
				 * N​o​ ​o​r​g​a​n​i​z​a​t​i​o​n​s​.
				 */
				empty: string
			}
		}
		settings: {
			general: {
				/**
				 * G​e​n​e​r​a​l
				 */
				title: string
				/**
				 * P​l​a​c​e​h​o​l​d​e​r​ ​f​o​r​ ​g​l​o​b​a​l​ ​a​d​m​i​n​ ​p​r​e​f​e​r​e​n​c​e​s​ ​(​b​r​a​n​d​i​n​g​,​ ​l​o​c​a​l​e​,​ ​e​t​c​.​)​.
				 */
				description: string
			}
			notification: {
				/**
				 * N​o​t​i​f​i​c​a​t​i​o​n​ ​s​e​t​t​i​n​g​s
				 */
				title: string
				/**
				 * R​e​s​e​r​v​e​d​ ​f​o​r​ ​f​u​t​u​r​e​ ​e​m​a​i​l​ ​a​n​d​ ​w​e​b​h​o​o​k​ ​s​e​t​t​i​n​g​s​.
				 */
				description: string
			}
			advance: {
				/**
				 * A​d​v​a​n​c​e​d
				 */
				title: string
				/**
				 * R​e​s​e​r​v​e​d​ ​f​o​r​ ​p​o​w​e​r​-​u​s​e​r​ ​o​p​t​i​o​n​s​ ​a​n​d​ ​e​x​p​e​r​i​m​e​n​t​a​l​ ​t​o​g​g​l​e​s​.
				 */
				description: string
			}
			security: {
				/**
				 * S​e​c​u​r​i​t​y
				 */
				title: string
				/**
				 * R​e​s​e​r​v​e​d​ ​f​o​r​ ​s​e​s​s​i​o​n​ ​p​o​l​i​c​i​e​s​,​ ​I​P​ ​r​u​l​e​s​,​ ​a​n​d​ ​a​u​d​i​t​ ​l​o​g​s​.
				 */
				description: string
			}
		}
	}
	errors: {
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		fallback: string
		/**
		 * N​e​t​w​o​r​k​ ​e​r​r​o​r​.​ ​C​h​e​c​k​ ​y​o​u​r​ ​c​o​n​n​e​c​t​i​o​n​.
		 */
		network: string
		/**
		 * I​n​v​a​l​i​d​ ​i​n​p​u​t​.
		 */
		invalidInput: string
		/**
		 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​s​i​g​n​ ​i​n​ ​t​o​ ​c​o​n​t​i​n​u​e​.
		 */
		unauthorized: string
		/**
		 * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​d​o​ ​t​h​a​t​.
		 */
		forbidden: string
		/**
		 * R​e​s​o​u​r​c​e​ ​n​o​t​ ​f​o​u​n​d​.
		 */
		notFound: string
		/**
		 * S​e​r​v​e​r​ ​e​r​r​o​r​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r​.
		 */
		serverError: string
		/**
		 * S​i​g​n​ ​i​n​ ​f​a​i​l​e​d​.
		 */
		signInFailed: string
		/**
		 * S​i​g​n​ ​u​p​ ​f​a​i​l​e​d​.
		 */
		signUpFailed: string
		/**
		 * I​n​v​a​l​i​d​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​.
		 */
		invalidCredentials: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​.
		 */
		createOrgFailed: string
		/**
		 * S​l​u​g​:​ ​l​e​t​t​e​r​s​,​ ​n​u​m​b​e​r​s​,​ ​h​y​p​h​e​n
		 */
		slugInvalid: string
		/**
		 * T​h​i​s​ ​f​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 */
		validationRequired: string
		/**
		 * E​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.
		 */
		validationEmail: string
		/**
		 * M​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​{​m​i​n​}​ ​c​h​a​r​a​c​t​e​r​s​.
		 * @param {unknown} min
		 */
		validationMinLength: RequiredParams<'min'>
	}
}

export type TranslationFunctions = {
	languages: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Tiếng Việt
		 */
		vi: () => LocalizedString
	}
	breadcrumb: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Admin
		 */
		admin: () => LocalizedString
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * Organizations
		 */
		organizations: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * General
		 */
		settingsGeneral: () => LocalizedString
		/**
		 * Notification
		 */
		settingsNotification: () => LocalizedString
		/**
		 * Advanced
		 */
		settingsAdvance: () => LocalizedString
		/**
		 * Security
		 */
		settingsSecurity: () => LocalizedString
		/**
		 * Posts
		 */
		posts: () => LocalizedString
		/**
		 * Categories
		 */
		categories: () => LocalizedString
		/**
		 * Members
		 */
		members: () => LocalizedString
		/**
		 * Invitations
		 */
		invitations: () => LocalizedString
		/**
		 * Reports
		 */
		reports: () => LocalizedString
		/**
		 * New
		 */
		'new': () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Post
		 */
		post: () => LocalizedString
		/**
		 * Category
		 */
		category: () => LocalizedString
	}
	sidebar: {
		/**
		 * Platform
		 */
		platform: () => LocalizedString
		/**
		 * Content
		 */
		content: () => LocalizedString
		/**
		 * Posts
		 */
		posts: () => LocalizedString
		/**
		 * Categories
		 */
		categories: () => LocalizedString
		/**
		 * Team
		 */
		team: () => LocalizedString
		/**
		 * Members
		 */
		members: () => LocalizedString
		/**
		 * Invitations
		 */
		invitations: () => LocalizedString
		/**
		 * Insights
		 */
		insights: () => LocalizedString
		/**
		 * Reports
		 */
		reports: () => LocalizedString
	}
	adminSidebar: {
		/**
		 * Administration
		 */
		administration: () => LocalizedString
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * Organizations
		 */
		organizations: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * General
		 */
		settingsGeneral: () => LocalizedString
		/**
		 * Notification
		 */
		settingsNotification: () => LocalizedString
		/**
		 * Advanced
		 */
		settingsAdvance: () => LocalizedString
		/**
		 * Security
		 */
		settingsSecurity: () => LocalizedString
	}
	adminHeader: {
		/**
		 * Exit admin
		 */
		exitAdmin: () => LocalizedString
	}
	common: {
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Saving…
		 */
		saving: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Show
		 */
		show: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Creating…
		 */
		creating: () => LocalizedString
		/**
		 * Refresh
		 */
		refresh: () => LocalizedString
		/**
		 * Loading…
		 */
		loading: () => LocalizedString
		/**
		 * Actions
		 */
		actions: () => LocalizedString
		/**
		 * Back to list
		 */
		backToList: () => LocalizedString
		/**
		 * Not found.
		 */
		notFound: () => LocalizedString
		/**
		 * Prev page
		 */
		prevPage: () => LocalizedString
		/**
		 * Next page
		 */
		nextPage: () => LocalizedString
		/**
		 * Page {page} · size {size}
		 */
		pageInfo: (arg: { page: unknown, size: unknown }) => LocalizedString
		/**
		 * Delete this item? This cannot be undone.
		 */
		deleteConfirm: () => LocalizedString
		/**
		 * Deleted
		 */
		deleted: () => LocalizedString
		/**
		 * Saved
		 */
		saved: () => LocalizedString
		/**
		 * Clone (id)
		 */
		copyId: () => LocalizedString
		/**
		 * Cloned id to clipboard
		 */
		copiedToClipboard: () => LocalizedString
		/**
		 * Custom…
		 */
		customAction: () => LocalizedString
	}
	theme: {
		/**
		 * Change theme
		 */
		changeTheme: () => LocalizedString
		/**
		 * Light
		 */
		light: () => LocalizedString
		/**
		 * Dark
		 */
		dark: () => LocalizedString
		/**
		 * System
		 */
		system: () => LocalizedString
	}
	orgSwitcher: {
		/**
		 * Organizations
		 */
		label: () => LocalizedString
		/**
		 * No organizations — create one from admin.
		 */
		empty: () => LocalizedString
	}
	navUser: {
		/**
		 * Upgrade to Pro
		 */
		upgrade: () => LocalizedString
		/**
		 * Admin
		 */
		admin: () => LocalizedString
		/**
		 * Billing
		 */
		billing: () => LocalizedString
		/**
		 * Notifications
		 */
		notifications: () => LocalizedString
		/**
		 * Log out
		 */
		logout: () => LocalizedString
		/**
		 * Account
		 */
		fallbackName: () => LocalizedString
	}
	notFound: {
		/**
		 * Page not found
		 */
		title: () => LocalizedString
		/**
		 * Check the URL or return home.
		 */
		description: () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
	}
	landing: {
		/**
		 * Boong Dashboard
		 */
		title: () => LocalizedString
		/**
		 * Welcome. Sign in to open an organization workspace or visit the admin area.
		 */
		description: () => LocalizedString
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * Sign up
		 */
		signUp: () => LocalizedString
	}
	home: {
		/**
		 * Home
		 */
		title: () => LocalizedString
		/**
		 * Pick an area from the sidebar to get started.
		 */
		description: () => LocalizedString
		/**
		 * Open posts
		 */
		openPosts: () => LocalizedString
		/**
		 * Open categories
		 */
		openCategories: () => LocalizedString
		/**
		 * Create an organization
		 */
		createOrganization: () => LocalizedString
	}
	signIn: {
		/**
		 * Sign in
		 */
		title: () => LocalizedString
		/**
		 * Use the email and password for your Boong account.
		 */
		description: () => LocalizedString
		/**
		 * Email
		 */
		fieldEmail: () => LocalizedString
		/**
		 * Password
		 */
		fieldPassword: () => LocalizedString
		/**
		 * Sign in
		 */
		submit: () => LocalizedString
		/**
		 * Signing in…
		 */
		submitting: () => LocalizedString
		/**
		 * Create an account
		 */
		createAccountLink: () => LocalizedString
		/**
		 * Signed in
		 */
		success: () => LocalizedString
	}
	signUp: {
		/**
		 * Sign up
		 */
		title: () => LocalizedString
		/**
		 * Create a Boong account with email and password.
		 */
		description: () => LocalizedString
		/**
		 * Name
		 */
		fieldName: () => LocalizedString
		/**
		 * Email
		 */
		fieldEmail: () => LocalizedString
		/**
		 * Password
		 */
		fieldPassword: () => LocalizedString
		/**
		 * Create account
		 */
		submit: () => LocalizedString
		/**
		 * Creating…
		 */
		submitting: () => LocalizedString
		/**
		 * Already have an account
		 */
		haveAccountLink: () => LocalizedString
		/**
		 * Account created — you can sign in.
		 */
		success: () => LocalizedString
	}
	orgWorkspace: {
		/**
		 * Organization workspace for {slug}. Pick a section from the sidebar to manage resources.
		 */
		description: (arg: { slug: unknown }) => LocalizedString
	}
	posts: {
		list: {
			/**
			 * Posts
			 */
			title: () => LocalizedString
			/**
			 * CRUD wired to GET/POST /api/posts with x-org-id. Pagination controls update URL state.
			 */
			description: () => LocalizedString
			/**
			 * Create
			 */
			create: () => LocalizedString
			/**
			 * No posts yet.
			 */
			empty: () => LocalizedString
			/**
			 * Title
			 */
			columnTitle: () => LocalizedString
			/**
			 * Content
			 */
			columnContent: () => LocalizedString
			/**
			 * Created
			 */
			columnCreated: () => LocalizedString
			/**
			 * Delete this post? This cannot be undone.
			 */
			deleteConfirm: () => LocalizedString
		}
		'new': {
			/**
			 * New post
			 */
			title: () => LocalizedString
			/**
			 * Create a post in this organization.
			 */
			description: () => LocalizedString
			/**
			 * Title
			 */
			fieldTitle: () => LocalizedString
			/**
			 * Content
			 */
			fieldContent: () => LocalizedString
			/**
			 * Post created
			 */
			success: () => LocalizedString
		}
		edit: {
			/**
			 * Edit post
			 */
			title: () => LocalizedString
			/**
			 * Title
			 */
			fieldTitle: () => LocalizedString
			/**
			 * Content
			 */
			fieldContent: () => LocalizedString
		}
		show: {
			/**
			 * Post not found.
			 */
			notFound: () => LocalizedString
		}
	}
	categories: {
		list: {
			/**
			 * Categories
			 */
			title: () => LocalizedString
			/**
			 * Uses /api/categories. The list endpoint is not org-scoped yet; rows are filtered in the UI to the active organization.
			 */
			description: () => LocalizedString
			/**
			 * Create
			 */
			create: () => LocalizedString
			/**
			 * No categories for this org.
			 */
			empty: () => LocalizedString
			/**
			 * Name
			 */
			columnName: () => LocalizedString
			/**
			 * Org
			 */
			columnOrg: () => LocalizedString
			/**
			 * Delete this category?
			 */
			deleteConfirm: () => LocalizedString
		}
		'new': {
			/**
			 * New category
			 */
			title: () => LocalizedString
			/**
			 * Name the category for this organization.
			 */
			description: () => LocalizedString
			/**
			 * Name
			 */
			fieldName: () => LocalizedString
			/**
			 * Category created
			 */
			success: () => LocalizedString
		}
		edit: {
			/**
			 * Edit category
			 */
			title: () => LocalizedString
			/**
			 * Name
			 */
			fieldName: () => LocalizedString
		}
		show: {
			/**
			 * Category not found.
			 */
			notFound: () => LocalizedString
		}
	}
	members: {
		/**
		 * Members
		 */
		title: () => LocalizedString
		/**
		 * Organization membership management will connect to Better Auth organization APIs when you extend this route.
		 */
		description: () => LocalizedString
	}
	invitations: {
		/**
		 * Invitations
		 */
		title: () => LocalizedString
		/**
		 * Invitation flows will plug into Better Auth organization invitations here.
		 */
		description: () => LocalizedString
	}
	charts: {
		area: {
			/**
			 * Area Chart - Interactive
			 */
			title: () => LocalizedString
			/**
			 * Showing total visitors for the last 3 months
			 */
			description: () => LocalizedString
			/**
			 * Select a value
			 */
			selectAria: () => LocalizedString
			/**
			 * Last 3 months
			 */
			last3Months: () => LocalizedString
			/**
			 * Last 30 days
			 */
			last30Days: () => LocalizedString
			/**
			 * Last 7 days
			 */
			last7Days: () => LocalizedString
		}
		bar: {
			/**
			 * Bar Chart - Multiple
			 */
			title: () => LocalizedString
			/**
			 * January - June 2024
			 */
			description: () => LocalizedString
			/**
			 * Trending up by 5.2% this month
			 */
			trending: () => LocalizedString
			/**
			 * Showing total visitors for the last 6 months
			 */
			showing: () => LocalizedString
		}
		pie: {
			/**
			 * Pie Chart - Label
			 */
			title: () => LocalizedString
			/**
			 * January - June 2024
			 */
			description: () => LocalizedString
			/**
			 * Trending up by 5.2% this month
			 */
			trending: () => LocalizedString
			/**
			 * Showing total visitors for the last 6 months
			 */
			showing: () => LocalizedString
		}
	}
	admin: {
		users: {
			/**
			 * Users
			 */
			title: () => LocalizedString
			/**
			 * Backed by the Better Auth admin plugin (listUsers).
			 */
			description: () => LocalizedString
			/**
			 * Email
			 */
			columnEmail: () => LocalizedString
			/**
			 * Name
			 */
			columnName: () => LocalizedString
			/**
			 * Role
			 */
			columnRole: () => LocalizedString
			/**
			 * No users returned.
			 */
			empty: () => LocalizedString
			/**
			 * user
			 */
			defaultRole: () => LocalizedString
		}
		organizations: {
			create: {
				/**
				 * Create organization
				 */
				title: () => LocalizedString
				/**
				 * Uses authClient.organization.create (Better Auth organization plugin). Requires an admin-capable session.
				 */
				description: () => LocalizedString
				/**
				 * Name
				 */
				fieldName: () => LocalizedString
				/**
				 * Slug
				 */
				fieldSlug: () => LocalizedString
				/**
				 * Create
				 */
				submit: () => LocalizedString
				/**
				 * Creating…
				 */
				submitting: () => LocalizedString
				/**
				 * Organization created
				 */
				success: () => LocalizedString
			}
			list: {
				/**
				 * Organizations (session)
				 */
				title: () => LocalizedString
				/**
				 * Listing memberships via /api/auth/organization/list. For a global admin directory, add a dedicated API route later.
				 */
				description: () => LocalizedString
				/**
				 * Name
				 */
				columnName: () => LocalizedString
				/**
				 * Slug
				 */
				columnSlug: () => LocalizedString
				/**
				 * Id
				 */
				columnId: () => LocalizedString
				/**
				 * No organizations.
				 */
				empty: () => LocalizedString
			}
		}
		settings: {
			general: {
				/**
				 * General
				 */
				title: () => LocalizedString
				/**
				 * Placeholder for global admin preferences (branding, locale, etc.).
				 */
				description: () => LocalizedString
			}
			notification: {
				/**
				 * Notification settings
				 */
				title: () => LocalizedString
				/**
				 * Reserved for future email and webhook settings.
				 */
				description: () => LocalizedString
			}
			advance: {
				/**
				 * Advanced
				 */
				title: () => LocalizedString
				/**
				 * Reserved for power-user options and experimental toggles.
				 */
				description: () => LocalizedString
			}
			security: {
				/**
				 * Security
				 */
				title: () => LocalizedString
				/**
				 * Reserved for session policies, IP rules, and audit logs.
				 */
				description: () => LocalizedString
			}
		}
	}
	errors: {
		/**
		 * Something went wrong. Please try again.
		 */
		fallback: () => LocalizedString
		/**
		 * Network error. Check your connection.
		 */
		network: () => LocalizedString
		/**
		 * Invalid input.
		 */
		invalidInput: () => LocalizedString
		/**
		 * You need to sign in to continue.
		 */
		unauthorized: () => LocalizedString
		/**
		 * You don't have permission to do that.
		 */
		forbidden: () => LocalizedString
		/**
		 * Resource not found.
		 */
		notFound: () => LocalizedString
		/**
		 * Server error. Please try again later.
		 */
		serverError: () => LocalizedString
		/**
		 * Sign in failed.
		 */
		signInFailed: () => LocalizedString
		/**
		 * Sign up failed.
		 */
		signUpFailed: () => LocalizedString
		/**
		 * Invalid email or password.
		 */
		invalidCredentials: () => LocalizedString
		/**
		 * Failed to create organization.
		 */
		createOrgFailed: () => LocalizedString
		/**
		 * Slug: letters, numbers, hyphen
		 */
		slugInvalid: () => LocalizedString
		/**
		 * This field is required.
		 */
		validationRequired: () => LocalizedString
		/**
		 * Enter a valid email address.
		 */
		validationEmail: () => LocalizedString
		/**
		 * Must be at least {min} characters.
		 */
		validationMinLength: (arg: { min: unknown }) => LocalizedString
	}
}

export type Formatters = {}
