/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as OrgSlugRouteRouteImport } from './routes/$orgSlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as OrgSlugReportsIndexRouteImport } from './routes/$orgSlug/reports/index'
import { Route as OrgSlugPostsIndexRouteImport } from './routes/$orgSlug/posts/index'
import { Route as OrgSlugMembersIndexRouteImport } from './routes/$orgSlug/members/index'
import { Route as OrgSlugInvitationsIndexRouteImport } from './routes/$orgSlug/invitations/index'
import { Route as OrgSlugCategoriesIndexRouteImport } from './routes/$orgSlug/categories/index'
import { Route as AdminSettingsSecurityRouteImport } from './routes/admin/settings/security'
import { Route as AdminSettingsNotificationRouteImport } from './routes/admin/settings/notification'
import { Route as AdminSettingsGeneralRouteImport } from './routes/admin/settings/general'
import { Route as AdminSettingsAdvanceRouteImport } from './routes/admin/settings/advance'
import { Route as OrgSlugPostsNewRouteImport } from './routes/$orgSlug/posts/new'
import { Route as OrgSlugCategoriesNewRouteImport } from './routes/$orgSlug/categories/new'
import { Route as OrgSlugPostsPostIdIndexRouteImport } from './routes/$orgSlug/posts/$postId/index'
import { Route as OrgSlugCategoriesCategoryIdIndexRouteImport } from './routes/$orgSlug/categories/$categoryId/index'
import { Route as OrgSlugPostsPostIdEditRouteImport } from './routes/$orgSlug/posts/$postId/edit'
import { Route as OrgSlugCategoriesCategoryIdEditRouteImport } from './routes/$orgSlug/categories/$categoryId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgSlugReportsIndexRoute = OrgSlugReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPostsIndexRoute = OrgSlugPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugMembersIndexRoute = OrgSlugMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugInvitationsIndexRoute = OrgSlugInvitationsIndexRouteImport.update({
  id: '/invitations/',
  path: '/invitations/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugCategoriesIndexRoute = OrgSlugCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const AdminSettingsSecurityRoute = AdminSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsNotificationRoute =
  AdminSettingsNotificationRouteImport.update({
    id: '/settings/notification',
    path: '/settings/notification',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminSettingsGeneralRoute = AdminSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsAdvanceRoute = AdminSettingsAdvanceRouteImport.update({
  id: '/settings/advance',
  path: '/settings/advance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgSlugPostsNewRoute = OrgSlugPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugCategoriesNewRoute = OrgSlugCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPostsPostIdIndexRoute = OrgSlugPostsPostIdIndexRouteImport.update({
  id: '/posts/$postId/',
  path: '/posts/$postId/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugCategoriesCategoryIdIndexRoute =
  OrgSlugCategoriesCategoryIdIndexRouteImport.update({
    id: '/categories/$categoryId/',
    path: '/categories/$categoryId/',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugPostsPostIdEditRoute = OrgSlugPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugCategoriesCategoryIdEditRoute =
  OrgSlugCategoriesCategoryIdEditRouteImport.update({
    id: '/categories/$categoryId/edit',
    path: '/categories/$categoryId/edit',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$orgSlug/categories/new': typeof OrgSlugCategoriesNewRoute
  '/$orgSlug/posts/new': typeof OrgSlugPostsNewRoute
  '/admin/settings/advance': typeof AdminSettingsAdvanceRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/notification': typeof AdminSettingsNotificationRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/$orgSlug/categories/': typeof OrgSlugCategoriesIndexRoute
  '/$orgSlug/invitations/': typeof OrgSlugInvitationsIndexRoute
  '/$orgSlug/members/': typeof OrgSlugMembersIndexRoute
  '/$orgSlug/posts/': typeof OrgSlugPostsIndexRoute
  '/$orgSlug/reports/': typeof OrgSlugReportsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/$orgSlug/categories/$categoryId/edit': typeof OrgSlugCategoriesCategoryIdEditRoute
  '/$orgSlug/posts/$postId/edit': typeof OrgSlugPostsPostIdEditRoute
  '/$orgSlug/categories/$categoryId/': typeof OrgSlugCategoriesCategoryIdIndexRoute
  '/$orgSlug/posts/$postId/': typeof OrgSlugPostsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$orgSlug/categories/new': typeof OrgSlugCategoriesNewRoute
  '/$orgSlug/posts/new': typeof OrgSlugPostsNewRoute
  '/admin/settings/advance': typeof AdminSettingsAdvanceRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/notification': typeof AdminSettingsNotificationRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/$orgSlug/categories': typeof OrgSlugCategoriesIndexRoute
  '/$orgSlug/invitations': typeof OrgSlugInvitationsIndexRoute
  '/$orgSlug/members': typeof OrgSlugMembersIndexRoute
  '/$orgSlug/posts': typeof OrgSlugPostsIndexRoute
  '/$orgSlug/reports': typeof OrgSlugReportsIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/$orgSlug/categories/$categoryId/edit': typeof OrgSlugCategoriesCategoryIdEditRoute
  '/$orgSlug/posts/$postId/edit': typeof OrgSlugPostsPostIdEditRoute
  '/$orgSlug/categories/$categoryId': typeof OrgSlugCategoriesCategoryIdIndexRoute
  '/$orgSlug/posts/$postId': typeof OrgSlugPostsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$orgSlug/categories/new': typeof OrgSlugCategoriesNewRoute
  '/$orgSlug/posts/new': typeof OrgSlugPostsNewRoute
  '/admin/settings/advance': typeof AdminSettingsAdvanceRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/notification': typeof AdminSettingsNotificationRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/$orgSlug/categories/': typeof OrgSlugCategoriesIndexRoute
  '/$orgSlug/invitations/': typeof OrgSlugInvitationsIndexRoute
  '/$orgSlug/members/': typeof OrgSlugMembersIndexRoute
  '/$orgSlug/posts/': typeof OrgSlugPostsIndexRoute
  '/$orgSlug/reports/': typeof OrgSlugReportsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/$orgSlug/categories/$categoryId/edit': typeof OrgSlugCategoriesCategoryIdEditRoute
  '/$orgSlug/posts/$postId/edit': typeof OrgSlugPostsPostIdEditRoute
  '/$orgSlug/categories/$categoryId/': typeof OrgSlugCategoriesCategoryIdIndexRoute
  '/$orgSlug/posts/$postId/': typeof OrgSlugPostsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/home'
    | '/signin'
    | '/signup'
    | '/$orgSlug/'
    | '/admin/'
    | '/$orgSlug/categories/new'
    | '/$orgSlug/posts/new'
    | '/admin/settings/advance'
    | '/admin/settings/general'
    | '/admin/settings/notification'
    | '/admin/settings/security'
    | '/$orgSlug/categories/'
    | '/$orgSlug/invitations/'
    | '/$orgSlug/members/'
    | '/$orgSlug/posts/'
    | '/$orgSlug/reports/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/$orgSlug/categories/$categoryId/edit'
    | '/$orgSlug/posts/$postId/edit'
    | '/$orgSlug/categories/$categoryId/'
    | '/$orgSlug/posts/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/signin'
    | '/signup'
    | '/$orgSlug'
    | '/admin'
    | '/$orgSlug/categories/new'
    | '/$orgSlug/posts/new'
    | '/admin/settings/advance'
    | '/admin/settings/general'
    | '/admin/settings/notification'
    | '/admin/settings/security'
    | '/$orgSlug/categories'
    | '/$orgSlug/invitations'
    | '/$orgSlug/members'
    | '/$orgSlug/posts'
    | '/$orgSlug/reports'
    | '/admin/organizations'
    | '/admin/users'
    | '/$orgSlug/categories/$categoryId/edit'
    | '/$orgSlug/posts/$postId/edit'
    | '/$orgSlug/categories/$categoryId'
    | '/$orgSlug/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/home'
    | '/signin'
    | '/signup'
    | '/$orgSlug/'
    | '/admin/'
    | '/$orgSlug/categories/new'
    | '/$orgSlug/posts/new'
    | '/admin/settings/advance'
    | '/admin/settings/general'
    | '/admin/settings/notification'
    | '/admin/settings/security'
    | '/$orgSlug/categories/'
    | '/$orgSlug/invitations/'
    | '/$orgSlug/members/'
    | '/$orgSlug/posts/'
    | '/$orgSlug/reports/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/$orgSlug/categories/$categoryId/edit'
    | '/$orgSlug/posts/$postId/edit'
    | '/$orgSlug/categories/$categoryId/'
    | '/$orgSlug/posts/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  HomeRoute: typeof HomeRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$orgSlug/reports/': {
      id: '/$orgSlug/reports/'
      path: '/reports'
      fullPath: '/$orgSlug/reports/'
      preLoaderRoute: typeof OrgSlugReportsIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/posts/': {
      id: '/$orgSlug/posts/'
      path: '/posts'
      fullPath: '/$orgSlug/posts/'
      preLoaderRoute: typeof OrgSlugPostsIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/members/': {
      id: '/$orgSlug/members/'
      path: '/members'
      fullPath: '/$orgSlug/members/'
      preLoaderRoute: typeof OrgSlugMembersIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/invitations/': {
      id: '/$orgSlug/invitations/'
      path: '/invitations'
      fullPath: '/$orgSlug/invitations/'
      preLoaderRoute: typeof OrgSlugInvitationsIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/categories/': {
      id: '/$orgSlug/categories/'
      path: '/categories'
      fullPath: '/$orgSlug/categories/'
      preLoaderRoute: typeof OrgSlugCategoriesIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/admin/settings/security': {
      id: '/admin/settings/security'
      path: '/settings/security'
      fullPath: '/admin/settings/security'
      preLoaderRoute: typeof AdminSettingsSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/notification': {
      id: '/admin/settings/notification'
      path: '/settings/notification'
      fullPath: '/admin/settings/notification'
      preLoaderRoute: typeof AdminSettingsNotificationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/general': {
      id: '/admin/settings/general'
      path: '/settings/general'
      fullPath: '/admin/settings/general'
      preLoaderRoute: typeof AdminSettingsGeneralRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/advance': {
      id: '/admin/settings/advance'
      path: '/settings/advance'
      fullPath: '/admin/settings/advance'
      preLoaderRoute: typeof AdminSettingsAdvanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$orgSlug/posts/new': {
      id: '/$orgSlug/posts/new'
      path: '/posts/new'
      fullPath: '/$orgSlug/posts/new'
      preLoaderRoute: typeof OrgSlugPostsNewRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/categories/new': {
      id: '/$orgSlug/categories/new'
      path: '/categories/new'
      fullPath: '/$orgSlug/categories/new'
      preLoaderRoute: typeof OrgSlugCategoriesNewRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/posts/$postId/': {
      id: '/$orgSlug/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/$orgSlug/posts/$postId/'
      preLoaderRoute: typeof OrgSlugPostsPostIdIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/categories/$categoryId/': {
      id: '/$orgSlug/categories/$categoryId/'
      path: '/categories/$categoryId'
      fullPath: '/$orgSlug/categories/$categoryId/'
      preLoaderRoute: typeof OrgSlugCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/posts/$postId/edit': {
      id: '/$orgSlug/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/$orgSlug/posts/$postId/edit'
      preLoaderRoute: typeof OrgSlugPostsPostIdEditRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/categories/$categoryId/edit': {
      id: '/$orgSlug/categories/$categoryId/edit'
      path: '/categories/$categoryId/edit'
      fullPath: '/$orgSlug/categories/$categoryId/edit'
      preLoaderRoute: typeof OrgSlugCategoriesCategoryIdEditRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
  }
}

interface OrgSlugRouteRouteChildren {
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugCategoriesNewRoute: typeof OrgSlugCategoriesNewRoute
  OrgSlugPostsNewRoute: typeof OrgSlugPostsNewRoute
  OrgSlugCategoriesIndexRoute: typeof OrgSlugCategoriesIndexRoute
  OrgSlugInvitationsIndexRoute: typeof OrgSlugInvitationsIndexRoute
  OrgSlugMembersIndexRoute: typeof OrgSlugMembersIndexRoute
  OrgSlugPostsIndexRoute: typeof OrgSlugPostsIndexRoute
  OrgSlugReportsIndexRoute: typeof OrgSlugReportsIndexRoute
  OrgSlugCategoriesCategoryIdEditRoute: typeof OrgSlugCategoriesCategoryIdEditRoute
  OrgSlugPostsPostIdEditRoute: typeof OrgSlugPostsPostIdEditRoute
  OrgSlugCategoriesCategoryIdIndexRoute: typeof OrgSlugCategoriesCategoryIdIndexRoute
  OrgSlugPostsPostIdIndexRoute: typeof OrgSlugPostsPostIdIndexRoute
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugCategoriesNewRoute: OrgSlugCategoriesNewRoute,
  OrgSlugPostsNewRoute: OrgSlugPostsNewRoute,
  OrgSlugCategoriesIndexRoute: OrgSlugCategoriesIndexRoute,
  OrgSlugInvitationsIndexRoute: OrgSlugInvitationsIndexRoute,
  OrgSlugMembersIndexRoute: OrgSlugMembersIndexRoute,
  OrgSlugPostsIndexRoute: OrgSlugPostsIndexRoute,
  OrgSlugReportsIndexRoute: OrgSlugReportsIndexRoute,
  OrgSlugCategoriesCategoryIdEditRoute: OrgSlugCategoriesCategoryIdEditRoute,
  OrgSlugPostsPostIdEditRoute: OrgSlugPostsPostIdEditRoute,
  OrgSlugCategoriesCategoryIdIndexRoute: OrgSlugCategoriesCategoryIdIndexRoute,
  OrgSlugPostsPostIdIndexRoute: OrgSlugPostsPostIdIndexRoute,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSettingsAdvanceRoute: typeof AdminSettingsAdvanceRoute
  AdminSettingsGeneralRoute: typeof AdminSettingsGeneralRoute
  AdminSettingsNotificationRoute: typeof AdminSettingsNotificationRoute
  AdminSettingsSecurityRoute: typeof AdminSettingsSecurityRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminSettingsAdvanceRoute: AdminSettingsAdvanceRoute,
  AdminSettingsGeneralRoute: AdminSettingsGeneralRoute,
  AdminSettingsNotificationRoute: AdminSettingsNotificationRoute,
  AdminSettingsSecurityRoute: AdminSettingsSecurityRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  HomeRoute: HomeRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
